services:
  xivstrat:
    image: caddy:alpine
    container_name: xivstrat
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./dist:/srv
